### PR TITLE
Heapster baseline fix

### LINKED ISSUE #8: Assure that heapster baseline files are named correctly
When creating a heapster baseline the name of the file is assumed. The source filename should be used for consistency.

### PR DESCRIPTION
**Pull request by DavidXArnold**
#### What does this PR do?
- Fixes #8 
- assures that the source and destination heapster baseline files names are consistently used.
- adds a note to the contribution document about manual version

#### Where should the reviewer start?
https://github.com/cloudability/metrics-agent/compare/master...DavidXArnold:heapsterBaselineFix?expand=1#diff-5cf9ac41985e0ce94b1270c7ec700302R193

#### How should this be manually tested?
`make deploy-local`

#### What are the relevant Github Issues?
#8 

#### Developer Done List

- [x] Tests Added/Updated
- [x] Updated README.md
- [x] Verified backward compatible
- [x] Verified database migrations will not be catastrophic
- [x] Considered Security, Availability and Confidentiality

#### Reviewer/Approval Done List

- [ ] Tests Pass Locally
- [ ] CI Build Passes
- [ ] Verified README.md is updated
- [ ] Verified changes are backward compatible
- [ ] Reviewed impact to Security, Availability and Confidentiality (if issue found, add comments and request changes)

### CODE REVIEW

File: kubernetes/kubernetes.go [hunk 1]
```diff
@@ -186,14 +185,22 @@ func (ka KubeAgentConfig) collectMetrics(
...
 
-	err = handleBaselineHeapsterMetrics(msd, baselineMetricSample, hme.Name())
+	baselineMetricSample, err := filepath.Glob(path.Dir(config.msExportDirectory.Name()) + "/baseline-metrics-export*")
+
 	if err != nil {
-		return err
+		log.Printf("Error encountered reading export directory: %v", err)
+	}
+
+	if len(baselineMetricSample[0]) >= 1 {
```
Comment (housejester) [inline kubernetes/kubernetes.go]: could this nil point if the call to file.Glob errored out? we check for that, but only log the error (line 196), and don't return.

Comment (housejester) [inline kubernetes/kubernetes.go]: filepath.Glob returns a slice of matches. here we're checking the length of the first match. do we intend to do that? is there a case where the first match is an empty string? or is it meant to be checking the number of matches instead?

File: kubernetes/kubernetes.go [hunk 2]
```diff
@@ -186,14 +185,22 @@ func (ka KubeAgentConfig) collectMetrics(
...
+		err = handleBaselineHeapsterMetrics(msd, baselineMetricSample[0], hme.Name())
```
Comment (housejester) [inline kubernetes/kubernetes.go]: this feels weird that we only process the first one. If we assume/only expect to have one, we could clarify that by asserting it. or adding a helper method that could do it for us. eg `baselineMetricSample, err := MatchOneFile("baseline-metrics-export*")`. possibly even `MustMatchOneFile` if we think it should panic if it matches multiple.

File: kubernetes/kubernetes.go [hunk 3]
```diff
@@ -186,14 +185,17 @@ func (ka KubeAgentConfig) collectMetrics(
...
+		return fmt.Errorf("unable to retrieve raw heapster metrics: %s", err)
 	}
 
 	defer util.SafeClose(hme.Close, &rerr)
 
-	err = handleBaselineHeapsterMetrics(msd, baselineMetricSample, hme.Name())
-	if err != nil {
-		return err
+	baselineMetricSample, err := util.MatchOneFile(path.Dir(config.msExportDirectory.Name()), "/baseline-metrics-export*")
+	if err == nil {
```
Comment (egs5053) [inline kubernetes/kubernetes.go]: I would refactor this to instead be:

`if err != nil {
  return err
}
err = handleBaselineHeapsterMetrics(msd, baselineMetricSample, hme.Name())
if err != nil {
  return err
}
`

Comment (egs5053) [reply kubernetes/kubernetes.go]: unless you want to continue through the rest of the function if it fails.

Comment (DavidXArnold) [reply kubernetes/kubernetes.go]: We want it to copy the baseline if one is found else continue through.

File: kubernetes/kubernetes.go [hunk 4]
```diff
@@ -186,14 +185,18 @@ func (ka KubeAgentConfig) collectMetrics(
...
 	}
 
 	defer util.SafeClose(hme.Close, &rerr)
 
-	err = handleBaselineHeapsterMetrics(msd, baselineMetricSample, hme.Name())
-	if err != nil {
-		return err
+	baselineMetricSample, fileCount, err := util.MatchOneFile(
+		path.Dir(config.msExportDirectory.Name()), "/baseline-metrics-export*")
+	if err == nil || fileCount == 0 {
```
Comment (egs5053) [inline kubernetes/kubernetes.go]: so if err != nil but fileCount is zero we still want to continue?

Comment (DavidXArnold) [reply kubernetes/kubernetes.go]: yes. per your suggestion I refactored for better read-ability
